#!/usr/bin/env node
/**
 * Regenerate the phase reference from `lib/phases.mjs`.
 *
 * The workflow documentation and the state machine must never disagree — a reference that
 * describes a gate the code does not enforce is worse than no reference, because agents act on
 * it. So the document is generated, and `tests/docs.test.mjs` fails if it is stale.
 *
 *   node scripts/docs-gen.mjs [--check]
 */

import fs from 'node:fs';
import path from 'node:path';
import { PHASES, PHASE_ORDER, REVIEW_ROUNDS, EXTRA_ROUNDS, TERMINAL_PHASES, STOP_ALLOWED_PHASES } from './lib/phases.mjs';
import { PLUGIN_ROOT } from './lib/paths.mjs';

const TARGET = path.join(PLUGIN_ROOT, 'skills', 'feature', 'references', 'workflow.md');

const REQUIREMENT_GLOSSARY = {
  'tasks:all-accepted': 'every work package in `tasks.json` has status `accepted`',
};
const describeRequirement = (r) => {
  if (REQUIREMENT_GLOSSARY[r]) return REQUIREMENT_GLOSSARY[r];
  if (r.startsWith('review:')) return `Codex round \`${r.slice(7)}\` completed and stored`;
  if (r.startsWith('adjudicated:')) return `every finding from \`${r.slice(12)}\` has a recorded decision`;
  if (r.startsWith('gate:')) return `the \`${r.slice(5)}\` gate has been evaluated and passed`;
  return `the \`${r}\` artefact exists and is substantive`;
};

function render() {
  const lines = [
    '<!-- GENERATED by scripts/docs-gen.mjs from scripts/lib/phases.mjs — do not edit by hand. -->',
    '',
    '# Workflow reference',
    '',
    'Every phase, who owns it, and what must be *true on disk* before it can be exited.',
    'Exit requirements are enforced by `state-machine.mjs`: a transition that does not satisfy',
    'them is refused, so a phase cannot be completed by asserting that it is.',
    '',
    '## Happy path',
    '',
    '```',
    PHASE_ORDER.join('\n↓\n'),
    '```',
    '',
    `Terminal states: ${TERMINAL_PHASES.map((p) => `\`${p}\``).join(', ')}.`,
    '',
    'Plus `SUSPENDED` — not a failure. The harness caps how many times a Stop hook may block',
    'consecutively; the controller yields just below that cap so a long run ends resumable',
    'rather than truncated mid-phase. `/hyperpowers:resume` continues it.',
    '',
    `The turn may only end in: ${STOP_ALLOWED_PHASES.map((p) => `\`${p}\``).join(', ')}. In every`,
    'other phase the Stop hook blocks and injects the next action.',
    '',
    '## Phases',
    '',
  ];

  for (const name of [...PHASE_ORDER, 'SUSPENDED']) {
    const p = PHASES[name];
    if (!p) continue;
    lines.push(`### ${name}`, '');
    lines.push(`**Owner:** ${p.owner}  `);
    lines.push(`**Purpose:** ${p.summary}`, '');
    if (p.requires.length) {
      lines.push('**Cannot be exited until:**', '');
      for (const r of p.requires) lines.push(`- ${describeRequirement(r)}`);
      lines.push('');
    } else if (name !== 'COMPLETE') {
      lines.push('**Exit requirements:** none enforced on disk — the transition itself is the record.', '');
    }
    if (p.successors.length) {
      lines.push(`**May transition to:** ${p.successors.map((s) => `\`${s}\``).join(', ')}`, '');
    }
    if (p.next) {
      lines.push('**Next action injected by the Stop hook:**', '', '> ' + p.next.replaceAll('\n', '\n> '), '');
    }
  }

  lines.push('## The six mandatory Codex rounds', '', '| Round | Artefact | Kind | Model | Effort | Phase |', '| --- | --- | --- | --- | --- | --- |');
  for (const [name, r] of Object.entries(REVIEW_ROUNDS)) {
    lines.push(`| \`${name}\` | ${r.artifact} | ${r.kind} | ${r.model} | ${r.effort} | ${r.phase} |`);
  }
  lines.push(
    '',
    '### The one extra round (spec §18)',
    '',
    'If round 2 of an artefact uncovers a *new* blocker, one additional targeted round is allowed',
    'for that artefact — and exactly one. It verifies round 2 the way round 2 verifies round 1.',
    'The adapter enforces the cap; a critical blocker surviving it means `BLOCKED`, not a third',
    'review.',
    '',
    '| Round | Artefact | Verifies | Model | Effort |',
    '| --- | --- | --- | --- | --- |',
  );
  for (const [name, r] of Object.entries(EXTRA_ROUNDS)) {
    lines.push(`| \`${name}\` | ${r.artifact} | \`${r.verifies}\` | ${r.model} | ${r.effort} |`);
  }

  lines.push(
    '',
    'Sol opens and closes the cycle: it challenges the overall direction first, and judges the',
    'delivered whole last. Luna handles the structured intermediate rounds, where the artefact is',
    'already shaped and the criteria are precise.',
    '',
    'Round 2 of each pair is a *verification* round, not a repeat. It receives the corrected',
    'artefact, the round-1 findings, and the adjudication record, and must confirm that accepted',
    'corrections actually landed, that they address the original claim, that they introduced no',
    'regression, and that rejections were justified.',
    '',
  );

  return lines.join('\n');
}

const content = render();
const check = process.argv.includes('--check');

if (check) {
  const current = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, 'utf8') : '';
  if (current !== content) {
    process.stderr.write(`${TARGET} is out of date. Run: node scripts/docs-gen.mjs\n`);
    process.exit(1);
  }
  process.stdout.write('workflow.md is up to date.\n');
} else {
  fs.mkdirSync(path.dirname(TARGET), { recursive: true });
  fs.writeFileSync(TARGET, content);
  process.stdout.write(`Wrote ${TARGET} (${content.length} bytes)\n`);
}
